[package]
name = "chip-8"
version = "0.1.0"
edition = "2024"

[dependencies]
anstyle = "1.0.10"
bitvec = "1.0.1"
clap = { version = "4.5.37", features = ["derive"] }
clap_complete = "4.5.48"
crossterm = "0.29.0"
rand = "0.9.1"
ratatui = "0.29.0"
